blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list,
        name='post_list_by_tag'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share,
        name='post_share'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comments by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


# E-mail分享表单
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


# 评论表单
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


# 搜索视图表单
class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count  # Django ORM的聚合函数
from .forms import EmailPostForm, CommentForm, SearchForm
from haystack.query import SearchQuerySet
# Create your views here.

"""
使用基于类的视图
"""


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 如果页码不是整数那么传到第一页
        posts = paginator.page(1)
    except EmptyPage:
        # 如果页码为空那么传到结果的最后一页
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, post, year, month, day):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_url(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    form = SearchForm()
    # 预先设置控制否则会报错
    cd = ''
    results = ''
    total_results = ''
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            # count total results
            total_results = results.count()

    return render(request, 'blog/post/search.html',
                  {'form': form,
                   'cd': cd,
                   'results': results,
                   'total_results': total_results})

templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>黄黄的博客</h2>
      <p>这是我的博客.至今为止我已经写了 {% total_posts %} 篇文章.</p>
      <h3>最近的博客</h3>
      {% show_latest_posts %}
{#  添加RSS   #}
        <p><a href="{% url "blog:post_feed" %}">订阅我的RSS Feed</a></p>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
      <h3>最多评论的文章</h3>
      {% get_most_commented_posts as most_commented_posts %}
      <ul>
          {% for post in most_commented_posts %}
              <li>
              <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </li>
          {% endfor %}
      </ul>
  </div>
</body>
</html>

templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
{#  {{ post.body|linebreaks }}#}
{#    替换成markdown   #}
    {{ post.body|markdown }}
    <p>
  <a href="{% url "blog:post_share" post.id %}">
   分享
  </a>
   </p>
{#    添加评论总数   #}
    {% with comments.count as total_comments %}
        <h2>
        {{ total_comments }} 条评论 {{ total_comments|pluralize }}
        </h2>
    {% endwith %}
{#    加入聚合整合tag列表   #}
    <h2>相似的博客内容</h2>
    {% for post in similar_posts %}
        <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
        {% empty %}
        没有相似的博客
    {% endfor %}
{#    加入评论列表  #}
    {% for comment in comments %}
        <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>还没有评论</p>
    {% endfor %}
{#    显示成功信息替代之前的内容   #}
    {% if new_comment %}
        <h2>你的评论已经被成功添加</h2>
    {% else %}
        <h2>增加一条新评论</h2>
        <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="评论"></p>
        </form>
    {% endif %}
{% endblock %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}

</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My blog{% endblock %}
{% block content %}
    <h1>黄黄的博客</h1>
    {% if tag %}
        <h2>含有 "{{ tag.name }}"标签的博客</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        </h2>
        <p class="tags">
        标签
        {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
        Published {{ post.publish }} by {{ post.author }}
        </p>
{#        {{ post.body|truncatewords:30|linebreaks }}#}
        {{ post.body|markdown|truncatewords_html:30 }}
        <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
    {% endfor %}
    {% include "pagination.html"  with page=posts%}
{#    使用类视图修改   #}
{#    {% include "pagination.html" with page=page_obj%}#}
{% endblock %}

templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if "query" in request.GET %}
        <h1>包含 "{{ cd.query }}"的内容</h1>
        <h3>找到 {{ total_results }} 条结果{{ total_results|pluralize }}</h3>
        {% for result in results %}
            {% with post=result.object %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|truncatewords:5 }}
            {% endwith %}
            {% empty %}
                <p>没有符合查询的内容</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="搜索">
        </form>
    {% endif %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}分享一个博客{% endblock %}

{% block content %}
  {% if sent %}
    <h1>邮件已经成功发送</h1>
    <p>
      "{{ post.title }}" 已经成功 {{ cd.to }}.
    </p>
  {% else %}
    <h1>通过邮件分享 "{{ post.title }}" </h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="发送邮件">
    </form>
  {% endif %}
{% endblock %}

templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>